### PR TITLE
Changed colors to work also with EdgeTX

### PR DESCRIPTION
**Pull request by rotorman**
According to feedback on EdgeTX Discord now the app works on EdgeTX as well as OpenTX:
https://discord.com/channels/839849772864503828/839849772864503832/890469955810762792
(self I tested only with EdgeTX).

### CODE REVIEW

**Comment by pfeerick** [comment]
Please keep in mind that the new colour constants to NOT exist on OpenTX, so this is NOT compatible with OpenTX (hence why the widget is will be disabled on OTX). A wrapper layer is needed, that lets the script change the colours the best way depending on what OS it is running on ;) Possibly something similar to what is being used in the [iNav lua widget now](https://github.com/iNavFlight/OpenTX-Telemetry-Widget), although I think it's going to be [even better shortly with colour caching](https://github.com/stronnag/inav-EdgeTX-OpenTX-Telemetry-Widget), etc. 

image

**Comment by moschotto** [comment]
Sounds like a separate script is needed and not just a modification that works on both platforms.  I don’t use EdgeTx and I don’t know if I create a separate branch for it (no time currently)

**Comment by pfeerick** [comment]
Basically just need a function that does the colour change appropriately depending on platform... if I find the reference to it (as I'm sure I saw a pre-written block that could be used) I'll link it, or might even do a PR to incorporate it... 

There is no need for a separate script - plus it will just make life harder as there's two copies of code to keep in sync ;)

**Comment by moschotto** [comment]
thanks - added with color change option to 

https://github.com/moschotto/OpenTX_GPS_Telemetry/tree/main/T16_EdgeTX

**Comment by pfeerick** [comment]
This is a better way (as in cross-compatible) to add color support which is compatible with both OTX and ETX if you are interested. I just hadn't submitted a PR for it yet as I haven't been well this last week. I've tested it myself and someone else has confirmed it is functional on ETX in both simulator and on TX16S, and I've also tested it on OTX simulator. Basically a wrapper function to stop direct manipulation of the TEXT_COLOR and LINE_COLOR variables and use CUSTOM_COLOR instead. 

Add `?w=1` to the end of the url when looking at the commit if you want to remove most of the whitespace cleanup my editor did...

https://github.com/pfeerick/OpenTX_GPS_Telemetry/commit/46c97d7a9c9be701862425711c18b2b1c93f6d68

**Pull request closed without merging**
